services:
  - type: web
    name: uiux-quality-inspector
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app --timeout 120 --workers 1 --threads 2 --preload
    envVars:
      - key: PYTHON_VERSION
        value: "3.10.0"
